version: "3.9"

services:
  fastapi:
    build:
      dockerfile: ./compose/fastapi/Dockerfile.dev
      context: .
    container_name: fastapi_app
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      PORT: 8000
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: /start

  postgres:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
