"""add quantidade rename timestamp_leitura

Revision ID: 1218d6326e63
Revises: 9dc857695827
Create Date: 2025-08-22 18:15:42.662103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1218d6326e63'
down_revision: Union[str, Sequence[str], None] = '9dc857695827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leitura', sa.Column('quantidade', sa.Integer(), nullable=True))
    op.add_column('leitura', sa.Column('ultima_leitura_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('leitura', 'timestamp_leitura')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leitura', sa.Column('timestamp_leitura', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('leitura', 'ultima_leitura_em')
    op.drop_column('leitura', 'quantidade')
    # ### end Alembic commands ###
