"""add user role

Revision ID: 33a8982d3940
Revises: e6f6038dd985
Create Date: 2025-12-02 13:55:39.849256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33a8982d3940'
down_revision: Union[str, Sequence[str], None] = 'e6f6038dd985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('admin', 'stockist', name='roleenum').create(op.get_bind())
    op.add_column('pecas', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pecas', 'usuarios', ['created_by'], ['id'])
    op.add_column('usuarios', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('usuarios', sa.Column('role', postgresql.ENUM('admin', 'stockist', name='roleenum', create_type=False), nullable=False))
    op.add_column('usuarios', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('usuarios', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'usuarios', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'created_by_id')
    op.drop_column('usuarios', 'created_at')
    op.drop_column('usuarios', 'role')
    op.drop_column('usuarios', 'is_active')
    op.drop_constraint(None, 'pecas', type_='foreignkey')
    op.drop_column('pecas', 'created_by')
    sa.Enum('admin', 'stockist', name='roleenum').drop(op.get_bind())
    # ### end Alembic commands ###
