"""adicionar timestamps ao inventario

Revision ID: 7217bdb87322
Revises: e6f6038dd985
Create Date: 2025-11-21 22:46:57.442026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7217bdb87322'
down_revision: Union[str, Sequence[str], None] = 'e6f6038dd985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferencia', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('conferencia', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conferencia', 'updated_at')
    op.drop_column('conferencia', 'created_at')
    # ### end Alembic commands ###
