"""create conferencia models

Revision ID: 87220ea4451a
Revises: 
Create Date: 2025-08-19 10:05:56.879926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87220ea4451a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('codigo_oem', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('localizacao', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('modelo_carro', sa.String(), nullable=False),
    sa.Column('ano_carro', sa.String(), nullable=False),
    sa.Column('rfid_uid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_oem'),
    sa.UniqueConstraint('rfid_uid')
    )
    op.create_index(op.f('ix_pecas_id'), 'pecas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('conferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finalizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('INICIADA', 'FINALIZADA', 'CANCELADA', name='statusconferencia'), nullable=False),
    sa.ForeignKeyConstraint(['id_funcionario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conferencia_id'), 'conferencia', ['id'], unique=False)
    op.create_table('etiqueta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('rdid_uuid', sa.String(), nullable=False),
    sa.Column('codigo_oem', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etiqueta_id'), 'etiqueta', ['id'], unique=False)
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('ocorreu_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conferencia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conferencia_id'], ['conferencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_id'), 'evento', ['id'], unique=False)
    op.create_table('leitura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.Column('conferencia_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_leitura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conferencia_id'], ['conferencia.id'], ),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiqueta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leitura_id'), 'leitura', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leitura_id'), table_name='leitura')
    op.drop_table('leitura')
    op.drop_index(op.f('ix_evento_id'), table_name='evento')
    op.drop_table('evento')
    op.drop_index(op.f('ix_etiqueta_id'), table_name='etiqueta')
    op.drop_table('etiqueta')
    op.drop_index(op.f('ix_conferencia_id'), table_name='conferencia')
    op.drop_table('conferencia')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_pecas_id'), table_name='pecas')
    op.drop_table('pecas')
    # ### end Alembic commands ###
