"""add rfid_uuid unique contraint to tag lida

Revision ID: e3db58badf4a
Revises: 1218d6326e63
Create Date: 2025-08-22 18:45:41.807750

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e3db58badf4a'
down_revision: Union[str, Sequence[str], None] = '1218d6326e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tag_lida', ['rfid_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_lida', type_='unique')
    # ### end Alembic commands ###
