"""remove unessessary details from peca model

Revision ID: e6f6038dd985
Revises: ffd8e85ce851
Create Date: 2025-08-25 09:49:38.275002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f6038dd985'
down_revision: Union[str, Sequence[str], None] = 'ffd8e85ce851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pecas', 'preco_venda')
    op.drop_column('pecas', 'preco_custo')
    op.drop_column('pecas', 'quantidade')
    op.drop_column('pecas', 'ano_carro')
    op.drop_column('pecas', 'modelo_carro')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pecas', sa.Column('modelo_carro', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pecas', sa.Column('ano_carro', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pecas', sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pecas', sa.Column('preco_custo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pecas', sa.Column('preco_venda', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
