"""add unique constraint leitura (conferencia_id, produto_id)

Revision ID: ea59d45b64d1
Revises: e3db58badf4a
Create Date: 2025-08-25 02:22:01.400901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea59d45b64d1'
down_revision: Union[str, Sequence[str], None] = 'e3db58badf4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_conferencia_produto', 'leitura', ['conferencia_id', 'produto_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_conferencia_produto', 'leitura', type_='unique')
    # ### end Alembic commands ###
