"""add unique constraint leitura (conferencia_id, produto_id)

Revision ID: ffd8e85ce851
Revises: ea59d45b64d1
Create Date: 2025-08-25 02:23:04.219640

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ffd8e85ce851"
down_revision: Union[str, Sequence[str], None] = "ea59d45b64d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
